extra-deps: []
arch: x86_64
flags: {}
packages:
  - '.'
  - location:
      git: https://github.com/rrnewton/haskell-lockfree.git
      commit: b85656e01de995c2654e4f2babc8cb6a56e6544b
    subdirs:
      - atomic-primops
extra-deps:
- unagi-chan-0.4.0.0
resolver:
  nightly-2015-08-06
